export default function Terms() {
  return (
    <div className="flex items-start justify-center px-6 py-8 pb-16">
      <article className="max-w-2xl space-y-6 font-body text-[15px] leading-7 text-foreground/90">
        <h1 className="font-heading text-3xl font-bold tracking-wider text-accent">
          Terms of Service
        </h1>

        <p className="text-muted text-sm">
          Last updated: March 20, 2026
        </p>

        <p>
          Welcome to Paracelsus. By accessing or using this application, you agree
          to be bound by these Terms of Service. If you do not agree to these terms,
          do not use the application.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          1. Service Description
        </h2>

        <p>
          Paracelsus is an AI-powered educational and entertainment application that
          provides longevity-related information based on publicly available research
          protocols. The application uses a fictional character inspired by the historical
          figure Paracelsus (1493&ndash;1541) to deliver this information in an engaging format.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          2. Not a Medical Service
        </h2>

        <p>
          <strong>Paracelsus is not a doctor, medical professional, healthcare provider,
          or medical service.</strong> The application does not provide medical advice,
          diagnosis, treatment, or any form of clinical care. It is not a medical device,
          diagnostic tool, or substitute for professional medical consultation.
        </p>

        <p>
          The lifespan projections, lifestyle assessments, and health-related content
          provided by this application are educational tools based on population-level
          research. They are not personal medical predictions, prescriptions, or
          treatment plans. No doctor-patient or provider-client relationship is created
          by using this application.
        </p>

        <p>
          <strong>Always consult a qualified healthcare professional</strong> before making
          any changes to your diet, exercise, medication, or lifestyle based on information
          from this application. Never disregard or delay seeking professional medical
          advice because of something you read or received through Paracelsus.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          3. AI-Generated Content
        </h2>

        <p>
          All responses, calculations, projections, and recommendations are generated by
          artificial intelligence. The AI character &ldquo;Paracelsus&rdquo; is a fictional
          persona and does not possess medical knowledge, clinical judgment, or the ability
          to evaluate your individual health status. AI-generated content may contain
          inaccuracies, errors, hallucinations, or outdated information.
        </p>

        <p>
          You acknowledge that you use AI-generated content at your own risk and that
          Paracelsus bears no responsibility for decisions made based on this content.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          4. User Responsibilities
        </h2>

        <p>
          By using Paracelsus, you represent and warrant that:
        </p>

        <ul className="list-disc pl-6 space-y-2">
          <li>You are at least 18 years of age.</li>
          <li>You understand that this is an educational tool, not a medical service.</li>
          <li>You will not rely on this application as a substitute for professional medical advice.</li>
          <li>You are responsible for verifying any health-related information with qualified professionals.</li>
          <li>You will not use this application if you are experiencing a medical emergency.</li>
          <li>The information you provide is voluntary and you accept the risks of sharing personal health data with an AI system.</li>
        </ul>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          5. Limitation of Liability
        </h2>

        <p>
          To the maximum extent permitted by applicable law, Paracelsus and its operators,
          affiliates, directors, officers, employees, agents, and contractors shall not be
          liable for any direct, indirect, incidental, consequential, special, punitive, or
          exemplary damages arising out of or related to:
        </p>

        <ul className="list-disc pl-6 space-y-2">
          <li>Your use of, or inability to use, the application.</li>
          <li>Any health decisions made based on information provided by the application.</li>
          <li>Any inaccuracies, errors, or omissions in AI-generated content.</li>
          <li>Any adverse health outcomes that may occur, regardless of whether you followed suggestions from the application.</li>
          <li>Loss of data, business interruption, or other damages of any kind.</li>
        </ul>

        <p>
          This limitation applies regardless of the form of action, whether in contract,
          tort, warranty, strict liability, or otherwise, even if Paracelsus has been
          advised of the possibility of such damages.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          6. Assumption of Risk
        </h2>

        <p>
          You expressly acknowledge and agree that use of this application is at your sole
          risk. Any lifestyle changes, health decisions, or actions you take based on
          information from Paracelsus are entirely your own responsibility. Paracelsus
          makes no guarantees about the accuracy, completeness, or applicability of any
          information provided.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          7. Third-Party References
        </h2>

        <p>
          This application references publicly available research including Dr. Oliver
          Zolman&apos;s Longevity Protocol and Bryan Johnson&apos;s Blueprint as frameworks
          for its educational content. Paracelsus is not affiliated with, endorsed by, or
          officially connected to Dr. Zolman, Bryan Johnson, or any associated organization.
          The use of these frameworks is for educational and illustrative purposes only.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          8. Data and Privacy
        </h2>

        <p>
          By using Paracelsus, you consent to the collection and processing of information
          you provide during conversations, including health-related data, for the purpose
          of delivering the service. Your data is stored securely and is not sold to third
          parties. You may request deletion of your data by contacting us.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          9. Subscription and Payments
        </h2>

        <p>
          Paracelsus offers a free tier with limited daily messages and a paid subscription
          for unlimited access. Payment terms, pricing, and cancellation policies will be
          communicated at the time of purchase. Subscription management is handled through
          our payment provider.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          10. Modifications
        </h2>

        <p>
          Paracelsus reserves the right to modify these Terms of Service at any time.
          Continued use of the application after changes constitutes acceptance of the
          updated terms. We will make reasonable efforts to notify users of material changes.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          11. Governing Law
        </h2>

        <p>
          These Terms of Service shall be governed by and construed in accordance with
          applicable law, without regard to conflict of law principles.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          12. Contact
        </h2>

        <p>
          For questions about these Terms of Service, contact us at{" "}
          <a href="mailto:healthtips2411@gmail.com" className="text-accent hover:opacity-80">
            healthtips2411@gmail.com
          </a>
        </p>

        <p className="text-muted text-sm pt-4 border-t border-white/5">
          By using Paracelsus, you acknowledge that you have read, understood, and agree
          to be bound by these Terms of Service.
        </p>
      </article>
    </div>
  );
}
