export default function Disclaimer() {
  return (
    <div className="flex items-start justify-center px-6 py-8 pb-16">
      <article className="max-w-2xl space-y-6 font-body text-[15px] leading-7 text-foreground/90">
        <h1 className="font-heading text-3xl font-bold tracking-wider text-accent">
          Disclaimer
        </h1>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          Not Medical Advice
        </h2>

        <p>
          Paracelsus is an educational and entertainment experience. It is not a
          medical device, diagnostic tool, health service, or substitute for
          professional medical advice, diagnosis, or treatment. The lifespan
          projections, habit assessments, and health-related content provided by
          this application are narrative tools based on population-level research
          — they are not personal medical predictions.
        </p>

        <p>
          Always seek the advice of a qualified physician or other qualified
          health provider with any questions you may have regarding a medical
          condition. Never disregard professional medical advice or delay in
          seeking it because of something you have read or received through
          this application.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          Limitation of Liability
        </h2>

        <p>
          All content, materials, products, services, and information on this
          website are provided on an &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; basis without warranties of any kind, either express
          or implied. Neither Paracelsus nor its creator, affiliates, directors,
          officers, employees, agents, contractors, successors, or assigns shall
          be liable for any damages whatsoever arising out of or related to the
          use of, or inability to use, this website&apos;s information or any
          other website linked to it.
        </p>

        <p>
          This waiver of liability applies to direct, indirect, incidental,
          consequential, special, punitive, exemplary, or other damages you or
          others may suffer, as well as damages for lost profits, business
          interruption, or the loss of data or information, even if Paracelsus
          is notified in advance of the potential for any such damages and
          regardless of the form of action, whether in contract, tort, warranty,
          strict liability, or otherwise.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          AI-Generated Content
        </h2>

        <p>
          Paracelsus is powered by artificial intelligence. The responses,
          calculations, and recommendations it provides are generated by a
          language model and may contain inaccuracies, errors, or outdated
          information. The AI character &ldquo;Paracelsus&rdquo; is a fictional
          persona — it does not possess medical knowledge, clinical judgment, or
          the ability to evaluate your individual health status.
        </p>

        <h2 className="font-heading text-xl font-semibold tracking-wider text-accent pt-4">
          Third-Party References
        </h2>

        <p>
          This application references Dr. Oliver Zolman&apos;s Longevity
          Protocol as a framework for its educational content. Paracelsus is not
          affiliated with, endorsed by, or officially connected to Dr. Zolman or
          any associated organization. The use of this framework is for
          educational and illustrative purposes only.
        </p>

        <p className="text-muted text-sm pt-4 border-t border-white/5">
          By using Paracelsus, you acknowledge and agree to this disclaimer in
          its entirety. If you do not agree, please discontinue use of the
          application immediately.
        </p>
      </article>
    </div>
  );
}
